tensorflow/fairness-indicators

tensorboard_plugin/tensorboard_plugin_fairness_indicators/demo.py, tensorboard_plugin/tensorboard_plugin_fairness_indicators/plugin_test.py, tensorboard_plugin/tensorboard_plugin_fairness_indicators/summary_v2_test.py
=> Internal change

fairness_indicators/example_model.py, fairness_indicators/example_model_test.py, fairness_indicators/remediation/weight_utils.py, tensorboard_plugin/tensorboard_plugin_fairness_indicators/plugin.py, tensorboard_plugin/tensorboard_plugin_fairness_indicators/plugin_test.py, tensorboard_plugin/tensorboard_plugin_fairness_indicators/summary_v2_test.py
=> Making code py3 compatible

fairness_indicators/version.py, setup.py
=> New Release

fairness_indicators/examples/Fairness_Indicators_Example_Colab.ipynb
Update Fairness_Indicators_Example_Colab.ipynb to TF2
=> Update Fairness_Indicators_Example_Colab.ipynb to TF2

fairness_indicators/examples/Fairness_Indicators_on_TF_Hub_Text_Embeddings.ipynb
reduce colab boilerplate via example_model's train_model
=> reduce colab boilerplate via example_model's train_model

fairness_indicators/examples/Fairness_Indicators_on_TF_Hub_Text_Embeddings.ipynb
reduce colab boilerplate via example_model's eval_model
=> reduce colab boilerplate via example_model's eval_model

fairness_indicators/examples/README.md
add documentation to run Fairness Indicators demos in Jupyter
=> add documentation to run Fairness Indicators demos in Jupyter

fairness_indicators/examples/Fairness_Indicators_TensorBoard_Plugin_Example_Colab.ipynb
=> internal changes

fairness_indicators/examples/Facessd_Fairness_Indicators_Example_Colab.ipynb, fairness_indicators/examples/Fairness_Indicators_Example_Colab.ipynb, fairness_indicators/examples/Fairness_Indicators_on_TF_Hub_Text_Embeddings.ipynb
hange the render api to accept two eval results.
=> hange the render api to accept two eval results.

fairness_indicators/examples/Facessd_Fairness_Indicators_Example_Colab.ipynb
=> FaceSSD colab title

fairness_indicators/documentation/_index.yaml, fairness_indicators/documentation/overview.md
=> ML Fairness

fairness_indicators/examples/Fairness_Indicators_TFCO_CelebA_Case_Study.ipynb
Fix trailing comma that was preventing from being able to parse JSON file.
=> Fix trailing comma that was preventing from being able to parse JSON file.

fairness_indicators/examples/Facessd_Fairness_Indicators_Example_Colab.ipynb
=> Add tests for faceSSD colab.

fairness_indicators/remediation/weight_utils.py, fairness_indicators/remediation/weight_utils_test.py
Adding additional typing, documentation and testing.
=> Adding additional typing, documentation and testing.

fairness_indicators/examples/Fairness_Indicators_TFCO_CelebA_Case_Study.ipynb
Add tests for TFCO CelebA colab
=> Add tests for TFCO CelebA colab

fairness_indicators/.github/auto_assign-issues.yml
Add auto_assign-issues.yml for automatic issue assigning.
=> Add auto_assign-issues.yml for automatic issue assigning.

README.md, fairness_indicators/.github/workflows/jupyter.yml, fairness_indicators/jupyter_test.py
Jupyter Notebook Continuous Integration Testing
=> Jupyter Notebook Continuous Integration Testing

fairness_indicators/.github/auto_assign-issues.yml
=> Add Summer to autoassign

.github/ISSUE_TEMPLATE/00-bug-issue.md, .github/ISSUE_TEMPLATE/10-build-installation-issue.md, .github/ISSUE_TEMPLATE/20-documentation-issue.md, .github/ISSUE_TEMPLATE/30-feature-request.md, .github/ISSUE_TEMPLATE/40-performance-issue.md, .github/ISSUE_TEMPLATE/50-other-issues.md
=> Issue Templates

fairness_indicators/jupyter_test.py
Add copyright + docstring to jupyter_test.py
=> Add copyright + docstring to jupyter_test.py

tensorboard_plugin/README.md, tensorboard_plugin/setup.py
Updating pypi package and its usages
=> Updating pypi package and its usages

fairness_indicators/RELEASE.md, fairness_indicators/version.py, tensorboard_plugin/tensorboard_plugin_fairness_indicators/RELEASE.md, tensorboard_plugin/tensorboard_plugin_fairness_indicators/version.py
Reverts tensorflow/fairness-indicators#139
=> Revert "R0.24.0"

RELEASE.md, fairness_indicators/version.py, tensorboard_plugin/tensorboard_plugin_fairness_indicators/RELEASE.md, tensorboard_plugin/tensorboard_plugin_fairness_indicators/version.py
Reverts tensorflow/fairness-indicators#319
=> Revert "Update RELEASE.md and version.py for 0.41.0 Release"
